/* eslint-disable no-console */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

import openapiTS, { astToString } from 'openapi-typescript';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Generates `src/generated/api-types.ts` from the COMMITTED
// `openapi.public.json` at the repo root — never the served
// `/api/v1/docs/openapi.json` URL. That file is the API pública projection
// (beta/estable operations only; see `src/api/public-surface.ts`), so this
// is the one input that lets the SDK build with no live backend at all
// (ADR 0106 §5.3, vitrina-app#2396/#2407).
//
// Usage: `pnpm run generate` (also runs as `prebuild`/`pretest`).

const SPEC_PATH = path.resolve(
  __dirname,
  '..',
  '..',
  '..',
  'openapi.public.json',
);
const OUT_PATH = path.resolve(
  __dirname,
  '..',
  'src',
  'generated',
  'api-types.ts',
);

async function main() {
  if (!fs.existsSync(SPEC_PATH)) {
    throw new Error(
      `[generate-types] ${SPEC_PATH} not found. This script reads the ` +
        'committed spec file — run it from a vitrina-app checkout that has ' +
        'openapi.public.json at its root, never against a live server.',
    );
  }
  const raw = fs.readFileSync(SPEC_PATH, 'utf8');
  const doc = JSON.parse(raw);
  const ast = await openapiTS(doc, { additionalProperties: false });
  const banner =
    '// AUTO-GENERATED by scripts/generate-types.ts from the repo-root ' +
    'openapi.public.json — do not edit by hand.\n\n';
  fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
  fs.writeFileSync(OUT_PATH, banner + astToString(ast), 'utf8');
  console.log(`[generate-types] wrote ${OUT_PATH} (from ${SPEC_PATH})`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
