/* eslint-disable no-console */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Generates `src/generated/error-codes.ts` — the SDK's typed view of the
// error catalogue, extracted from the COMMITTED `export type ErrorCode = …`
// union in `src/errors/index.ts` at the repo root (ADR 0106; cross-ticket
// with vitrina-app#2399/#2476/#2477's error codes). Regex over the source
// text rather than an import: that module pulls in the full error-class
// hierarchy and its own dependency graph, which is exactly the kind of
// "requires a live backend" import this package's generation step must
// never take (see generate-types.ts's header for the same rule applied to
// the OpenAPI doc).
//
// Usage: `pnpm run generate` (also runs as `prebuild`/`pretest`).

const SOURCE_PATH = path.resolve(
  __dirname,
  '..',
  '..',
  '..',
  'src',
  'errors',
  'index.ts',
);
const OUT_PATH = path.resolve(
  __dirname,
  '..',
  'src',
  'generated',
  'error-codes.ts',
);

/**
 * Strips `//` and block comments BEFORE any quote-matching runs. The prose
 * around this union is full of apostrophes ("it's", "the dealer's") that a
 * naive `'([^']+)'` regex over the raw source happily reads as string
 * delimiters — confirmed the hard way (first run spliced comment prose into
 * the generated union). Stripping comments first removes the apostrophes
 * along with the rest of the comment, so no quote-parsing sophistication is
 * needed for the code itself.
 */
function stripComments(text: string): string {
  const noBlockComments = text.replace(/\/\*[\s\S]*?\*\//g, '');
  return noBlockComments
    .split('\n')
    .map((line) => {
      const idx = line.indexOf('//');
      return idx === -1 ? line : line.slice(0, idx);
    })
    .join('\n');
}

function extractErrorCodes(source: string): string[] {
  const cleaned = stripComments(source);
  const start = cleaned.indexOf('export type ErrorCode =');
  if (start === -1) {
    throw new Error(
      `[generate-error-codes] could not find "export type ErrorCode =" in ${SOURCE_PATH}`,
    );
  }
  const end = cleaned.indexOf(';', start);
  if (end === -1) {
    throw new Error(
      '[generate-error-codes] union declaration has no terminating ";"',
    );
  }
  const block = cleaned.slice(start, end);
  const codes = [...block.matchAll(/'([^']+)'/g)].map((m) => m[1]);
  if (codes.length === 0) {
    throw new Error(
      '[generate-error-codes] found the ErrorCode union but no string literals in it',
    );
  }
  // Comment-stripping trims trailing prose but can leave a blank line where a
  // comment used to be — not a correctness issue for the regex above, only
  // asserted here so a FUTURE format change (e.g. an inline `'CODE', // note`)
  // that silently drops entries fails loudly instead of shipping a short list.
  const duplicates = codes.filter((c, i) => codes.indexOf(c) !== i);
  if (duplicates.length > 0) {
    throw new Error(
      `[generate-error-codes] duplicate codes extracted: ${duplicates.join(', ')}`,
    );
  }
  return codes;
}

async function main() {
  if (!fs.existsSync(SOURCE_PATH)) {
    throw new Error(
      `[generate-error-codes] ${SOURCE_PATH} not found. This script reads ` +
        'the committed error catalogue — run it from a vitrina-app checkout.',
    );
  }
  const source = fs.readFileSync(SOURCE_PATH, 'utf8');
  const codes = extractErrorCodes(source);
  const union = codes.map((c) => `  | '${c}'`).join('\n');
  const arrayLiteral = codes.map((c) => `  '${c}',`).join('\n');
  const banner =
    '// AUTO-GENERATED by scripts/generate-error-codes.ts from the repo-root ' +
    "src/errors/index.ts's `ErrorCode` union — do not edit by hand.\n\n";
  const out =
    `${banner}` +
    '/**\n' +
    ' * Every code the API error envelope can carry as `error.code`, at the\n' +
    ' * commit this SDK was generated from. Kept OPEN (see `OpenErrorCode` in\n' +
    ' * `../errors.ts`) because a server can ship a new code before this SDK\n' +
    ' * is regenerated — narrow on the ones you handle, never assume this\n' +
    ' * list is exhaustive at runtime.\n' +
    ' */\n' +
    `export type ErrorCode =\n${union};\n\n` +
    'export const ERROR_CODES: readonly ErrorCode[] = [\n' +
    `${arrayLiteral}\n` +
    '] as const;\n';
  fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
  fs.writeFileSync(OUT_PATH, out, 'utf8');
  console.log(
    `[generate-error-codes] wrote ${OUT_PATH} (${codes.length} codes from ${SOURCE_PATH})`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
